### ISSUE TITLE
failed to create FS watcher: no such file or directory

### ISSUE THREAD

**Issue by mobeixiaoxin** [WLBF/null-device-plugin#1]
您好，编译完成后，在虚机中执行cpu-device-plugin二进制文件可正常创建FS watcher，但构造镜像后执行，报错：failed to create FS watcher: no such file or directory，请问您知道怎样解决么？谢谢

**Comment by WLBF** [comment]
Kubelet access device plugin by unix domain socket file. You need to mount specific directory in container.
https://github.com/WLBF/null-device-plugin/blob/017a473111350446b30c7ad29885aa46a1992848/manifests/daemonset.yaml#L20-L26
